## Construcción de estructuras NumPy para simulación y análisis

## Vector con distribución de puntos

La función **np.linspace()** permite crear un vector de valores numéricos igualmente espaciados entre dos extremos, ideal para representar escalas, tiempo, intervalos de medición o datos normalizados. A diferencia de escribir listas manuales o usar np.arange(), esta función garantiza que se generen exactamente n puntos entre los extremos especificados, incluyendo
ambos límites.

### ✅ np.linspace()

👉 Sirve para crear números entre un inicio y un fin, indicando cuántos valores quieres.

**np.linspace(inicio, fin, cantidad)**

In [2]:
import numpy as np

x = np.linspace(0, 1, 5) # considera inicio y final
print(x)


[0.   0.25 0.5  0.75 1.  ]


👉 Aquí le dijiste:

empieza en 0

termina en 1

quiero 5 valores

NumPy calcula solo el paso.

👉 Muy importante

✔ linspace SIEMPRE incluye el valor final (por defecto).

### ✅ np.arange()

👉 Sirve para crear números desde un inicio hasta un fin usando un paso fijo.

👉 Forma:

**np.arange(inicio, fin, paso)**

In [3]:
x = np.arange(0, 1, 0.25) # considera inicio y no el final (1)
print(x)


[0.   0.25 0.5  0.75]


👉 Aquí le dijiste:

empieza en 0

llega hasta antes de 1

avanza de 0.25

👉 Muy importante

✔ arange NO asegura incluir el final.

- 🧩 En tu nivel (y para evitar errores)

👉 Usa:

✅ linspace cuando te pidan:
“genera N valores entre A y B”

✅ arange cuando te pidan:
“genera valores cada cierto paso”

- 👀 Resumen muy corto

👉 linspace → cantidad
👉 arange → paso

🧩 Conectándolo con tu ejercicio anterior

Tú tenías algo como:

tiempos de lectura cada 0.25

👉 Ahí está bien:

In [4]:
np.arange(0, 4, 0.25)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75])

Pero si te piden:

genera exactamente 16 tiempos entre 0 y 4

👉 ahí conviene:

In [5]:
# con 16 valores me da un intervalo 0,266666
np.linspace(0,4,16)

array([0.        , 0.26666667, 0.53333333, 0.8       , 1.06666667,
       1.33333333, 1.6       , 1.86666667, 2.13333333, 2.4       ,
       2.66666667, 2.93333333, 3.2       , 3.46666667, 3.73333333,
       4.        ])

Tiene:

👉 16 valores
👉 empieza en 0
👉 termina en 4

Eso calza perfecto con: **linspace(inicio=0, fin=4, cantidad=16)**

📏 Cuál es el paso real

Cuando usas linspace(0, 4, 16) el paso no es 0.25.

Es:

(4−0)/(16−1)=4/15=0.2666666666...


⚠️ Ojo con un error muy común

Muchos estudiantes creen:

16 valores entre 0 y 4 → paso = 4/16 = 0.25

❌ Eso sería correcto solo si fuera arange.

Pero en linspace:

👉 el intervalo se reparte en 15 espacios, no en 16.

🔎 Si tú querías paso 0.25 entre 0 y 4

Entonces no debes usar linspace así, sino:

In [6]:
np.arange(0, 4.01, 0.25)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

(o bien)

In [7]:
# para que el intervalo sea de 0.25 tengo que poner 17 valores
np.linspace(0, 4, 17)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

Porque:

👉 de 0 a 4 cada 0.25 hay 17 valores.

Características:

- np.linspace() : - Inclusión del límite final / Sí, incluye el valor final

                  - Precisión de espaciado / Preciso (define cantidad de puntos)

                  - Parámetro principal / Número de puntos


- np.arange() :   - Inclusión del límite final / No, excluye el valor final

                  - Precisión de espaciado / A veces impreciso por redondeo
                  
                  - Parámetro principal / Paso o incremento

In [8]:
# otro ejemplo partiendo de 2
ejemplo_2 = np.arange(2,4.1,0.25) # para considerar del 2 al 4 / no es lo ideal
print(ejemplo_2)

[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.  ]


In [9]:
# para que haga la medicion desde el 2 al 4, sin considerarlo, saltando de 0.25, eso son 8 saltos, pk no llega hasta el 4
ejemplo_2 = np.arange(2,4,0.25) 
print(ejemplo_2)

[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75]


In [10]:
# para que haga la medicion desde el 2 al 4 considerarlo, y le pido 9 elementos para que considere el 4
ejemplo_2 = np.linspace(2,4,9) 
print(ejemplo_2)

[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.  ]


In [11]:
ejemplo_3 = np.arange(0,0.7,0.3)
print(ejemplo_3)

[0.  0.3 0.6]


In [12]:
ejemplo_3 = np.linspace(0,0.6,3)
print(ejemplo_3)

[0.  0.3 0.6]


### Ejemplo de linspace()

In [13]:
# A continuación se presenta un ejemplo de código en el que se genera un vector de 5 valores equiespaciados entre 0 y 1:
npvector = np.linspace(0,1,5)
print(npvector)

[0.   0.25 0.5  0.75 1.  ]


Este fragmento de código genera un vector de 5 valores distribuidos de forma equidistante entre 0 y 1. Es
especialmente útil cuando se requiere un número exacto de puntos dentro de un intervalo definido.

In [21]:
ejemplo4 = np.arange(0,3,0.33333)
print(ejemplo4)

[0.      0.33333 0.66666 0.99999 1.33332 1.66665 1.99998 2.33331 2.66664
 2.99997]


In [22]:
ejemplo4 = np.linspace(0,3,10)
print(ejemplo4)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


### Buena práctica

Usa linspace() cuando te interese controlar la cantidad exacta de divisiones entre dos puntos,
especialmente en tareas de visualización o discretización de intervalos.