## Ejercicio

Trabajas en un laboratorio de desarrollo de soluciones para monitoreo ambiental automatizado. Tu equipo necesita probar
algoritmos de visualización y control antes de que los sensores físicos estén disponibles. 

Para eso, deberás simular lecturas de temperatura, humedad y luminosidad en distintas condiciones (rango fijo, aleatoriedad, calibración de referencia). 

Además, se requiere preparar estas estructuras para su análisis posterior, utilizando transformaciones que las dejen listas para modelos de predicción.

¿Cómo podrías representar y transformar esta información usando NumPy para obtener datos de prueba confiables, variados y
bien estructurados?

In [58]:
import numpy as np

In [59]:
# 1. Simular 10 lecturas de temperatura entre 15°C y 30°C con linspace
temperaturas = np.linspace(15,30,10)
print('Lecturas simuladas de temperiaturas (C°): \n', temperaturas)

Lecturas simuladas de temperiaturas (C°): 
 [15.         16.66666667 18.33333333 20.         21.66666667 23.33333333
 25.         26.66666667 28.33333333 30.        ]


In [60]:
# 2. Crear una matriz identidad para validar referencia (ideal de calibración)
calibracion = np.identity(3) # 3 caracteristicas que almacena
print("\nMatriz identidad de referencia para sensores:\n", calibracion)



Matriz identidad de referencia para sensores:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
# 3. Generar 5 lecturas aleatorias de humedad entre 40% y 80%
np.random.seed(0)
humedad = np.random.randint(40, 81, size=5)
print("\nLecturas aleatorias de humedad (%):\n", humedad)


Lecturas aleatorias de humedad (%):
 [40 43 43 79 49]


In [62]:
# 4. Simular 3 series de luminosidad entre 200 y 800 lúmenes.
# Los sensores trabajaron de manera sucesiva.
np.random.seed(0)
luminosidad = np.random.randint(200,801, size=(3,5))
print("\nLecturas de luminosidad en 3 sensores (lúmenes):\n", luminosidad)


Lecturas de luminosidad en 3 sensores (lúmenes):
 [[759 392 559 209 477]
 [799 270 672 800 596]
 [514 686 751 287 374]]


In [63]:
# 5. Reestructurar datos de luminosidad para análisis por minuto
# flatten para que cree un vector 
luminosidad_lineal = luminosidad.flatten()
print("\nLecturas de luminosidad aplanadas (por minuto):\n", luminosidad_lineal)


Lecturas de luminosidad aplanadas (por minuto):
 [759 392 559 209 477 799 270 672 800 596 514 686 751 287 374]


In [64]:
# 6. Preparar arreglo para insertar nuevas mediciones
estructura = np.zeros((3, 5))
estructura

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
# ejemplo: El slicing dentro del selector [] permite seleccionar filas o columnas para aplicar el random
ejemplo = estructura
ejemplo [1 , :] = np.random.randint(100, 500, size=5) 
print("\nEstructura lista para nuevas mediciones (datos aleatorios insertados):\n", ejemplo)


Estructura lista para nuevas mediciones (datos aleatorios insertados):
 [[  0.   0.   0.   0.   0.]
 [188. 437. 265. 125. 433.]
 [  0.   0.   0.   0.   0.]]


In [66]:
ejemplo [2,:]= np.random.randint(100, 500, size= (5,)) 
print("\nEstructura lista para nuevas mediciones (datos aleatorios insertados):\n", ejemplo)


Estructura lista para nuevas mediciones (datos aleatorios insertados):
 [[  0.   0.   0.   0.   0.]
 [188. 437. 265. 125. 433.]
 [172. 365. 215. 343. 297.]]


In [67]:
# 6. Preparar arreglo para insertar nuevas mediciones
# [: , :] es para que el llenado de la matriz de ceros sea completa todas las filas y todas las columnas 
estructura[: , :] = np.random.randint(100, 500, size=(3, 5)) 
print("\nEstructura lista para nuevas mediciones (datos aleatorios insertados):\n", estructura)


Estructura lista para nuevas mediciones (datos aleatorios insertados):
 [[435. 438. 199. 277. 343.]
 [385. 247. 247. 498. 388.]
 [365. 285. 227. 132. 131.]]
