# Matriz identidad

### Creación de matrices identidad

¿Por qué una matriz con 1 en la diagonal y 0 en el resto es clave en álgebra
lineal?

La matriz identidad actúa como el "uno" en la multiplicación matricial: no
altera el resultado al multiplicar otra matriz compatible. Por eso, es
especialmente útil para simular comportamientos neutros en operaciones,
validar algoritmos o inicializar estructuras en aprendizaje automático.

La matriz identidad es una matriz cuadrada (mismo número de filas y columnas) que cumple estas reglas:

Tiene 1 en la diagonal principal

Tiene 0 en todas las demás posiciones

Ejemplo de matriz identidad 3×3:

[1 0 0

 0 1 0

 0 0 1]

📌 Se parece al número 1, pero para matrices.

🔹 ¿Para qué sirve?

La matriz identidad tiene una propiedad clave:

👉 Cualquier matriz multiplicada por la matriz identidad queda igual

A⋅I=A ( A por I es igual a A)

Es el elemento neutro de la multiplicación de matrices.

### Matrices identidad en NumPy

La función np.identity(n) crea una matriz identidad de tamaño n x n ( matriz cuadrada). Este tipo de matriz es el equivalente al número
1 en la multiplicación: no altera el resultado al multiplicar otra matriz compatible. Es ampliamente usada en
operaciones matriciales, validación de modelos y desarrollo de algoritmos de aprendizaje automático.

### Ejemplo de matriz identidad

In [3]:
import numpy as np

# Esta matriz tiene unos en la diagonal principal y ceros en el resto de los elementos.
identidad = np.identity(3)
print(identidad)

# NumPy usa float por defecto (1.0).


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


También puedes crear matrices no cuadradas:

In [4]:
np.eye(2, 3)


array([[1., 0., 0.],
       [0., 1., 0.]])

🔹 Ejemplo práctico: multiplicación

In [5]:
A = np.array([[2, 3],
              [4, 5]])

I = np.eye(2)

resultado = A @ I
print(resultado)


[[2. 3.]
 [4. 5.]]


In [6]:
A = np.array([[2, 3],
              [4, 5]])

I = np.identity(2)

resultado = A @ I
print(resultado)

[[2. 3.]
 [4. 5.]]


⚠️ Ojo con esto (muy importante en NumPy)

Para multiplicar matrices debes usar: @

**np.identity(3) es lo mismo que np.eye(3), cumplen la misma función**

🔹 ¿Cuándo la vas a usar mucho?

Álgebra lineal

Inversa de matrices

Sistemas de ecuaciones

Machine Learning

Transformaciones (rotación, escalado)

## Matriz aleatoria

Una matriz aleatoria es una matriz (arreglo 2D) cuyos valores se generan al azar.

### Generación de matrices aleatorias (números al azar)

¿Cómo puedes simular condiciones variables o generar datos de prueba sin un conjunto real disponible?
NumPy permite generar datos aleatorios controlados, ideales para simulaciones, pruebas de algoritmos o
visualizaciones. Las funciones más utilizadas son:

En NumPy se crean usando el módulo:

**np.random**

In [7]:
import numpy as np

matriz = np.random.rand(3, 4)
print(matriz)


[[0.2161153  0.66506252 0.3565703  0.28312716]
 [0.62192377 0.9011647  0.62006783 0.26697467]
 [0.54634462 0.04510467 0.68224981 0.48012841]]


👉 Esto crea una matriz de:

3 filas

4 columnas

con números aleatorios

✅ ¿Qué tipo de números genera?

**np.random.rand()**

genera números:

✔ entre 0 y 1
✔ decimales
✔ distribución uniforme

✅ Otra forma muy usada: números enteros aleatorios

**np.random.randint(a, b, size)**

Entrega números enteros, entre a y b-1. 

En el ejemplo de más abajo es a =1 y b= 10, pero para la entrega es 9, osea los n° aleatorios van del 0 al 9

In [8]:
matriz = np.random.randint(1, 10, size=(3, 4))
print(matriz)


[[9 7 5 2]
 [1 6 3 6]
 [3 7 2 2]]


👉 Esto genera una matriz de:

3 filas

4 columnas

con números enteros entre a y b-1 ( dependiendo los valores que ponga el usuario)

### Ejemplo de matrices aleatorias

In [ ]:
# aleatorio decimal con elemnetos entre 0 y 1. Matriz de 4 filas por 3 columnas.
aleatorio = np.random.rand(4,3)
print( aleatorio)

[[0.21577319 0.27478414 0.86444428]
 [0.55060995 0.16676223 0.80637944]
 [0.43320294 0.11315655 0.44012875]
 [0.07256592 0.93413254 0.38711858]]


In [28]:
# aleatorio n° enteros en este caso entre 10 y 99. En una Matriz con tamaño 3,4/ 3 filas por 4 columnas.
np.random.seed(42)# También puedes establecer una semilla para repetir los mismos resultados:
enteros = np.random.randint(10,100,size=(3,4))
print(enteros)

[[61 24 81 70]
 [30 92 96 84]
 [84 97 33 12]]


### ✅ ¿Para qué sirve seed?

Sirve para que los números aleatorios se repitan siempre igual. Se establece una semilla para mantener los resultados.

Es decir:

👉 no sean realmente “al azar”, sino reproducibles.

🔴 Sin seed

In [21]:
# 👉 Cada vez que ejecutas el programa te salen números distintos.
A = np.random.rand(2,2)
print(A)


[[0.60111501 0.70807258]
 [0.02058449 0.96990985]]


✅ Con seed

In [ ]:
np.random.seed(0)

A = np.random.rand(2,2)
print(A)

# 👉 Ahora, cada vez que ejecutes este código, la matriz será exactamente la misma.


[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]


🧠 ¿Qué hace exactamente esta línea? 

**np.random.seed(0)**

👉 fija el punto de inicio del generador de números aleatorios. 

### ✅ Ejemplo con enteros

In [ ]:
np.random.seed(5)
M = np.random.randint(1, 10, size=(3,3))
print(M)

# 👉 Siempre se repite la misma matriz.


[[4 7 7]
 [1 9 5]
 [8 1 1]]


✅ En palabras simples

👉 seed sirve para que el “azar” sea controlado.

📌 Frase típica de enunciado

Si en tu guía dice:

use una semilla para reproducibilidad

✅ ¿Qué número de seed debo usar?

👉 La respuesta corta es: da lo mismo qué número pongas.

In [ ]:
'''
np.random.seed(0)
np.random.seed(10)
np.random.seed(23)
np.random.seed(1234)
'''

Todos son válidos.

🧠 Entonces… ¿para qué cambia el número?

👉 Cambia la secuencia de números que se va a generar.

Es decir:

seed(0) → una secuencia

seed(10) → otra secuencia distinta

seed(23) → otra distinta

Pero todas son:

✔ reproducibles
✔ válidas
✔ correctas

📌 En resumen

👉 No existe un “mejor” seed.

👉 El seed solo sirve para repetir resultados.

🧠 Frase para memorizar

👉 El seed no controla la calidad de los números,
solo controla que se repitan.