# Redimensionado de arreglos

La función reshape() permite transformar la forma de un arreglo manteniendo la secuencia de datos. Es clave en tareas de
preprocesamiento de datos, entrenamiento de modelos y manejo de estructuras multidimensionales.

- Transformación dimensional: 
  
Reshape() permite convertir arreglos unidimensionales en matrices bidimensionales.

- Preprocesamiento de datos:

Durante el preprocesamiento, reshape() adapta la estructura de los datos al formato requerido por modelos de aprendizaje automático sin alterar los valores originales.

- Estructuras multidimensionales

El manejo eficiente de tensores y estructuras multidimensionales se logra mediante reshape(), conservando siempre la secuencia y cantidad total de elementos.

### Ejemplo de reshape()

A continuación se presenta un ejemplo de cómo transformar un vector en una matriz de 3 filas y 4 columnas:

In [78]:
import numpy as np

# Este fragmento de código toma un arreglo de 12 elementos secuenciales y lo reorganiza en una matriz 3x4.
original = np.arange(12) # esto es lo mismo que np.arange(0,12,1) vector que va del 0 al 11
print(original)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [79]:
matriz_restructurada = original.reshape((3,4)) # ordeno los elementos en una matriz de 3*4 con los elementos del 0 al 11
print(matriz_restructurada)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Importante sobre reshape()

Importante: El producto de las dimensiones debe coincidir con la cantidad de elementos del arreglo original. Si original tiene 12 elementos, reshape() solo funcionará con combinaciones como (3,4), (2,6), (6,2), entre otros.

In [80]:
matriz_restructurada = original.reshape((2,6))
print(matriz_restructurada)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Funciones complementarias

- ravel() o flatten(): convierten un arreglo a una sola dimensión sin alterar el original.

### ✅ ¿Para qué sirven ravel() y flatten()?

Sirven para aplanar una matriz.

Es decir:

👉 convertir una matriz 2D en un vector 1D.

In [81]:
#  matriz_a es una matriz de 2 filas y 3 columnas.
matriz_a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(matriz_a)


[[1 2 3]
 [4 5 6]]


### ✅ ravel()

In [82]:
vector_a = matriz_a.ravel()
print(vector_a)


[1 2 3 4 5 6]


#### 👉 convierte la matriz en un vector.

### ✅ flatten()

In [83]:
vector_b = matriz_a.flatten()
print(vector_b)

[1 2 3 4 5 6]


#### 👉 el resultado se ve exactamente igual.

⚠️ Entonces… ¿cuál es la diferencia real?

La diferencia no está en el resultado,
está en cómo se guarda en memoria.

### 🧠 Diferencia clave

🔹 ravel()

👉 normalmente devuelve una vista de la matriz original.

Eso significa:

si modificas el vector, puede cambiar la matriz original.


🔹 flatten()

👉 devuelve una copia.

Si modificas el vector, la matriz original no cambia.

### ✅ Ejemplo

In [84]:
matriz_a = np.array([[1, 2],
              [3, 4]])

print(matriz_a)

v = matriz_a.ravel()
v[0] = 100

print(matriz_a)

[[1 2]
 [3 4]]
[[100   2]
 [  3   4]]


👉 cambió la matriz.

Ahora con flatten:

In [85]:
matriz_a = np.array([[1, 2],
              [3, 4]])
print(matriz_a)

v2 = matriz_a.flatten()
v2[0] = 100

print(matriz_a)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


👉 la matriz no cambió.

### 📌 En resumen corto

👉 ravel()
✔ aplana
✔ comparte datos con la matriz

👉 flatten()
✔ aplana
✔ crea una copia

### ✅ ¿Qué hace resize?

resize cambia la forma de un arreglo.

👉 lo redimensiona.

resize(): cambia el tamaño, pero puede alterar datos y el arreglo original.

In [86]:
vector_2= np.array([1,2,3,4,5,6])
print("Vector original:", vector_2)

Vector original: [1 2 3 4 5 6]


✅ Usando el método del arreglo

In [87]:
# 👉 ahora a es una matriz 2×3.
vector_2.resize((2,3))  # Cambiamos la forma a 2 filas × 3 columnas
print(vector_2)

[[1 2 3]
 [4 5 6]]


#### ⚠️ Muy importante (diferencia con reshape) 👉 resize modifica el arreglo original.

### ✅ reshape

In [88]:
a = np.array([1,2,3,4,5,6])
b = a.reshape((2,3))

print(a)
print(b)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


👉 a queda igual
👉 b es el nuevo arreglo

### ✅ resize

In [89]:
a = np.array([1,2,3,4,5,6])
a.resize((2,3))

print(a)

[[1 2 3]
 [4 5 6]]


👉 a cambia

### ⚠️ Otra diferencia importante

Si el tamaño nuevo no calza con la cantidad de datos:

tiene que con la misma cantidad de elementos para poder redristribuirlos

a.reshape((4,4)) 

👉 error

🔹 Con resize → rellena repitiendo datos

In [90]:
a = np.array([1,2,3,4])
c = np.resize(a, (3,6))
print(c)


[[1 2 3 4 1 2]
 [3 4 1 2 3 4]
 [1 2 3 4 1 2]]


In [91]:
a = np.array([1,2])
c = np.resize(a, (3,6))
print(c)

[[1 2 1 2 1 2]
 [1 2 1 2 1 2]
 [1 2 1 2 1 2]]


In [ ]:
# si no tiene la cantidad de elemntos rellena 
arreglo_resize = np.resize(matriz_restructurada, (6,8))
print(arreglo_resize)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11  0  1  2  3]
 [ 4  5  6  7  8  9 10 11]
 [ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11  0  1  2  3]
 [ 4  5  6  7  8  9 10 11]]
