In [8]:
import pandas as pd
import numpy as np
from datetime import date

## 1. Extracción de Datos:

In [9]:
# 1. Extracción de Datos: Leer el archivo CSV
df_clima = pd.read_csv('datos_climaticos.csv', sep=',', encoding='utf-8')
df_clima

,timestamp,temperatura_celsius,humedad_relativa
0,2024-07-15 0:00:00,22.5,85.10
1,2024-07-15 0:05:00,22.4,85.30
2,2024-07-16 0:05:00,23.4,85.40
3,2024-07-17 0:05:00,24.4,85.50
4,2024-07-18 0:05:00,25.4,85.60
5,2024-07-19 0:05:00,26.4,85.70
6,2024-07-20 0:05:00,27.4,85.80
7,2024-07-21 0:05:00,28.4,85.90
8,2024-07-22 0:05:00,29.4,85.10
9,2024-07-23 0:05:00,30.4,85.11


In [24]:
df_clima.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   timestamp            18 non-null     str    
 1   temperatura_celsius  18 non-null     float64
 2   humedad_relativa     18 non-null     float64
dtypes: float64(2), str(1)
memory usage: 564.0 bytes


In [26]:
'''2. Extraer columnas temperatura_celsius y humedad_relativa y conviértelas en un único arreglo 
(array) de NumPy ''' 

datos_numericos = np.array(df_clima[['temperatura_celsius', 'humedad_relativa']])
datos_numericos

array([[22.5 , 85.1 ],
       [22.4 , 85.3 ],
       [23.4 , 85.4 ],
       [24.4 , 85.5 ],
       [25.4 , 85.6 ],
       [26.4 , 85.7 ],
       [27.4 , 85.8 ],
       [28.4 , 85.9 ],
       [29.4 , 85.1 ],
       [30.4 , 85.11],
       [22.5 , 85.12],
       [22.4 , 85.13],
       [23.4 , 85.14],
       [24.4 , 85.15],
       [25.4 , 85.16],
       [23.4 , 85.17],
       [23.4 , 85.18],
       [25.4 , 85.19]])

In [27]:
type(datos_numericos)

numpy.ndarray

In [28]:
datos_numericos.shape

(18, 2)

## 2. Manipulación y Análisis con NumPy

#### - Usando el arreglo datos_numericos:

##### a. Selección: 
Selecciona e imprime únicamente la primera hora de mediciones(las primeras 12 filas) de ambas variables.

In [29]:
# primera hora de mediciones (las primeras 12 filas) de ambas variables.

primera_hora = datos_numericos[:12,:]
print('Primeras 12 mediciones (Temperatura y Humedad): \n', primera_hora)

Primeras 12 mediciones (Temperatura y Humedad): 
 [[22.5  85.1 ]
 [22.4  85.3 ]
 [23.4  85.4 ]
 [24.4  85.5 ]
 [25.4  85.6 ]
 [26.4  85.7 ]
 [27.4  85.8 ]
 [28.4  85.9 ]
 [29.4  85.1 ]
 [30.4  85.11]
 [22.5  85.12]
 [22.4  85.13]]


In [15]:
primera_hora.shape

(12, 2)

##### b. Filtrado Condicional: 
Encuentra y muestra todas las temperaturas que fueron superiores a 25.0°C.

In [16]:
temperaturas = datos_numericos[:,0] # trae todas las filas de la columna 0
temperaturas

array([22.5, 22.4, 23.4, 24.4, 25.4, 26.4, 27.4, 28.4, 29.4, 30.4, 22.5,
       22.4, 23.4, 24.4, 25.4, 23.4, 23.4, 25.4])

In [17]:
temperatura_superior = temperaturas[temperaturas > 25.0]
print('\nTemperaturas superiores a 25.0°C:\n', temperatura_superior)


Temperaturas superiores a 25.0°C:
 [25.4 26.4 27.4 28.4 29.4 30.4 25.4 25.4]


In [18]:
temperatura_superior.shape

(8,)

##### c. Operaciones: 
Convierte todos los valores de temperatura de Celsius a Fahrenheit. La fórmula es: F=C×9/5 + 32. Almacena el resultado en un nuevo vector llamado temperatura_fahrenheit

In [19]:
# Fórmula: F = C * (9/5) + 32  // Hay un error en la guíaen la fórmula
temperatura_fahrenheit = (temperaturas * 9/5) + 32
print('Temperaturas Fahrenheit:\n', temperatura_fahrenheit)

Temperaturas Fahrenheit:
 [72.5  72.32 74.12 75.92 77.72 79.52 81.32 83.12 84.92 86.72 72.5  72.32
 74.12 75.92 77.72 74.12 74.12 77.72]


##### d. Creación y Redimensión: 
Crea una matriz de 2x2 que contenga la primera y la última medición de temperatura y humedad del día.

In [20]:
# Matriz 2x2
# Extraer la primera y la 'ultima fila de la matriz datos_numericos
primera_medicion = datos_numericos[0]
ultima_medicion = datos_numericos[-1]


matriz_primera_ultima = np.array([primera_medicion,ultima_medicion])
print('\nMatriz 2x2 (Inicio y Fin del día):\n', matriz_primera_ultima)


Matriz 2x2 (Inicio y Fin del día):
 [[22.5  85.1 ]
 [25.4  85.19]]


### 3. Escritura de Datos:

○ Guarda el nuevo vector temperatura_fahrenheit que creaste en un nuevo archivo llamado temperaturas_fahrenheit.csv.

In [21]:
hoy = date.today()
print(hoy)

2026-02-09


In [22]:
# Nombre archivo
nombre_archivo = (f'temperaturas_fahrenheit.csv')

# Crear DataFrame para guardar vector temperatura_fahrenheit para usar .to_csv
df_temperatura_fahrenheit = pd.DataFrame(temperatura_fahrenheit, columns=['temperatura_fahrenheit'])

df_temperatura_fahrenheit.to_csv(nombre_archivo, index=False, encoding='utf-8-sig')

print(f'Archivo generado con éxito: {nombre_archivo}_{hoy}')


Archivo generado con éxito: temperaturas_fahrenheit.csv_2026-02-09


In [23]:
df_fahrenheit = pd.read_csv('temperaturas_fahrenheit.csv')
df_fahrenheit

,temperatura_fahrenheit
0,72.50
1,72.32
2,74.12
3,75.92
4,77.72
5,79.52
6,81.32
7,83.12
8,84.92
9,86.72
