In [72]:
import pandas as pd
import numpy as np

In [73]:
datos_lista =[10,20,30,40]

In [74]:
type(datos_lista)

list

In [75]:
vector_desde_lista = np.array(datos_lista)
vector_desde_lista

array([10, 20, 30, 40])

## Creación básica de un vector

In [76]:
# Para crear un vector en NumPy, utilizamos la función np.array() pasando una lista de valores numéricos:
# Este vector tiene cuatro elementos y representa una única dimensión.
vector = np.array([10, 20, 30, 40])
vector

array([10, 20, 30, 40])

In [77]:
type(vector)

numpy.ndarray

### Explorando sus características

In [78]:
print(vector.ndim)
# Devuelve 1 → una dimensión
print(vector.shape)
# Devuelve (4,) → 4 elementos en una dimensión
print(vector.size)
print(vector.dtype)
# Devuelve el tipo de dato, ej: int64 o float64

1
(4,)
4
int64


### Operaciones vectorizadas

Esto permite realizar transformaciones sobre los datos de forma muy rápida
y clara. No es necesario un ciclo for como en python.

In [79]:
'''Una de las principales fortalezas de NumPy es la aplicación de operaciones 
matemáticas directamente sobre el vector, sin necesidad de bucles:'''

print(vector)
print(vector + 5) # Suma 5 a cada elemento: [15 25 35 45]
print(vector * 2) # Multiplica por 2: [20 40 60 80]

[10 20 30 40]
[15 25 35 45]
[20 40 60 80]


### Indexación y acceso a elementos

Al igual que las listas de Python, los vectores de NumPy se
pueden indexar:

In [80]:
print(vector[0])
# 10
print(vector[-1])
# 40 (último valor)

10
40


También es posible usar rebanado (slicing):

In [81]:
print(vector[1:3]) # [20 30]

[20 30]


Estas capacidades son muy útiles al analizar subconjuntos de
datos o preparar entradas para algoritmos.

### Conversión desde listas existentes

Es común partir con listas tradicionales y convertirlas a NumPy para
aprovechar su velocidad y funciones:

In [82]:
lista = [5, 10, 15]
arreglo = np.array(lista)

In [83]:
type(lista)

list

In [84]:
type(arreglo)

numpy.ndarray

In [85]:
print(arreglo.dtype)

int64


### Cuidados al crear vectores

- Todos los elementos deben ser del mismo tipo (int, float, etc.). Si hay
mezcla (por ejemplo, ['5', 10]), NumPy convertirá todo a str.

- Las operaciones matemáticas se aplican elemento a elemento, no al
vector completo como un bloque.

## Creación de una matriz

In [86]:
import numpy as np

In [87]:
# Esta matriz tiene 2 filas y 3 columnas:
# hacia abajo son las filas y hacia el lado las columnas 
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)


[[1 2 3]
 [4 5 6]]


### Exploración de propiedades básicas

In [88]:
print(matriz.ndim) # Número de dimensiones → 2
print(matriz.shape) # Forma → (2, 3): 2 filas, 3 columnas
print(matriz.size) # Total de elementos → 6
print(matriz.dtype) # Tipo de dato de los elementos → ej: int64

2
(2, 3)
6
int64


### Operaciones vectorizadas en matrices

Uno de los beneficios de NumPy es que las operaciones pueden aplicarse directamente sobre toda la matriz, sin bucles:

In [89]:
print(matriz * 10) # [[10 20 30]# [40 50 60]]

[[10 20 30]
 [40 50 60]]


In [90]:
print(matriz)

[[1 2 3]
 [4 5 6]]


También puedes realizar operaciones más complejas como:

In [91]:
print(matriz + np.array([[10, 10, 10], [0, 0, 0]]))

[[11 12 13]
 [ 4  5  6]]


In [92]:
matriz_suma= np.array([[10,10,10],[0,0,0]])
print(matriz_suma)

[[10 10 10]
 [ 0  0  0]]


In [93]:
vector

array([10, 20, 30, 40])

In [94]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
# matriz_por_vector= (matriz * vector)
# print(matriz_por_vector)

esto arroja error por:

- La matriz tiene forma (2,3) → 2 filas, 3 columnas.

- El vector tiene forma (4,) → 4 elementos.

Python intenta hacer la multiplicación elemento a elemento, pero no puede “encajar” las formas. Por eso aparece:

ValueError: operands could not be broadcast together with shapes (2,3) (4,)

Cómo sí puedes multiplicar

a) Multiplicación elemento a elemento (broadcasting)

El vector debe tener 3 elementos si quieres multiplicar con (2,3).

Por ejemplo:

In [96]:
matriz1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector1 = np.array([1, 2, 3])  # 3 elementos

resultado = matriz1 * vector1  # Multiplicación fila a fila
print(resultado)


[[ 1  4  9]
 [ 4 10 18]]


In [97]:
matriz_suma

array([[10, 10, 10],
       [ 0,  0,  0]])

In [98]:
vector1

array([1, 2, 3])

In [99]:
print(matriz_suma + vector1)

[[11 12 13]
 [ 1  2  3]]


Este comportamiento es posible gracias a la difusión de valores (broadcasting) que NumPy aplica de forma automática, y que exploraremos
más adelante.

### Escalar en operaciones con matrices

Cuando haces operaciones con matrices y un escalar, el escalar se aplica a todos los elementos de la matriz. Esto se llama escalar × matriz:

In [100]:
a = np.array([[1, 2],
              [3, 4]])

k = 10  # escalar

b = k * a
print(b)


[[10 20]
 [30 40]]


### Acceso a elementos

Al igual que con vectores, puedes acceder a valores específicos:

In [101]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
print(matriz[0, 1]) # Fila 0, Columna 1 → 2

2


In [103]:
print(matriz[0, 2])
print(matriz[1, 2])

3
6


También puedes acceder a una fila o columna completa:

In [104]:
print(matriz[0]) # Fila completa: [1 2 3]
print(matriz[:, 1]) # Columna 1: [2 5]

[1 2 3]
[2 5]


print(matriz[0])

✅ Esto imprime la primera fila de la matriz, no una columna.

Explicación paso a paso:

Supongamos que:


matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])
                   
matriz.shape → (2,3) → 2 filas, 3 columnas

matriz[0] → primera fila → [1, 2, 3]

matriz[1] → segunda fila → [4, 5, 6]

#### Esquema de índices

In [105]:
''' 
matriz:
        columnas
         0   1   2
       +---+---+---+
fila 0 | 1 | 2 | 3 |
fila 1 | 4 | 5 | 6 |

'''

' \nmatriz:\n        columnas\n         0   1   2\n       +---+---+---+\nfila 0 | 1 | 2 | 3 |\nfila 1 | 4 | 5 | 6 |\n\n'

Cómo acceder a filas:

Código	       Qué devuelve

- matriz[0]	[1, 2, 3] → primera fila
- matriz[1]	[4, 5, 6] → segunda fila

Nota: matriz[i] siempre devuelve la fila i.

Cómo acceder a columnas:

Código	          Qué devuelve

- matriz[:,0]	[1, 4] → todas las filas, la primera columna
- matriz[:,1]	[2, 5] → todas las filas, la segunda columna
- matriz[:,2]	[3, 6] → todas las filas, la tercera columna

: → significa “todas las filas”

j → columna j

In [106]:
# Para un solo número:
print(matriz[0,2])  # fila 0, columna 2

3


Esta capacidad de indexación es fundamental en manipulación y
limpieza de datos.

### Recomendaciones al trabajar con matrices

- Siempre valida la forma de la matriz con .shape antes de realizar
operaciones entre múltiples arreglos.

- Asegúrate de que las dimensiones coincidan para realizar
operaciones aritméticas o lógicas.

- Para matrices muy grandes, considera el uso de estructuras
dispersas si hay muchos ceros (ver SciPy).

## Generación de secuencias automáticas con arange()

Para esto, NumPy ofrece la función np.arange() que permite crear vectores
numéricos con gran flexibilidad.

### Sintaxis de np.arange()

- inicio: valor desde donde comienza la secuencia (incluyente).
- fin: valor donde termina la secuencia (excluyente).
- paso: valor por el que se incrementa (o decrementa) la secuencia.

 np.arange(inicio, fin, paso)

In [107]:
vector_arange = np.arange(1,9,1)
print(vector_arange)


[1 2 3 4 5 6 7 8]


In [108]:
vector_arange = np.arange(1,9,3)
print(vector_arange)

[1 4 7]


In [109]:
vector_arange = np.arange(20,-10,-1.5)
print(vector_arange)

[20.  18.5 17.  15.5 14.  12.5 11.   9.5  8.   6.5  5.   3.5  2.   0.5
 -1.  -2.5 -4.  -5.5 -7.  -8.5]


In [110]:
# En este caso, se genera una secuencia que parte en 0, se incrementa de 5 en 5, y se detiene antes de llegar a 20.

rango = np.arange(0, 20, 5)
print(rango)# Resultado: [ 0 5 10 15 ]

[ 0  5 10 15]


Aplicaciones típicas:

Este tipo de arreglo es útil en tareas como:

- Ejes temporales: 
Por ejemplo, segundos, minutos u horas.

- Índices de simulación: 
Ciclos de prueba o iteraciones numéricas.

- Marcadores de posición:
Plantillas de columnas o estructuras dummy.

In [111]:
df = pd.DataFrame({'Color': ['Rojo', 'Azul', 'Verde']})
dummies = pd.get_dummies(df['Color'])
print(dummies)


    Azul   Rojo  Verde
0  False   True  False
1   True  False  False
2  False  False   True


✅ Resumen

Estructura dummy: estructura creada solo como marcador, sin contenido real, para pruebas o compatibilidad.

Variable dummy (Data Science): variable binaria 0/1 que representa categorías en forma numérica.

In [112]:
# Crear una secuencia de minutos del 0 al 9
tiempo = np.arange(0, 10, 1)
print(tiempo)# Resultado: [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [113]:
# Crear una secuencia de minutos del 0 al 9
tiempo = np.arange(10) # es lo mismoque el anterior, se asume que inicia en 0 y da pasos de 1 en 1 hasta antes de 10
print(tiempo)

[0 1 2 3 4 5 6 7 8 9]


In [114]:
# Esto dice o es = a 0 true, 0 es = a 1 False, 0 es = a 2 False... va del 0 al 2 ya que el 3 es excluyente
ejemplo = np.arange(3) == 0
print(ejemplo)

[ True False False]


In [115]:
# para que no me quede con true o false y me quede un vector [1,0,0]
ejemplo = (np.arange(3) == 0).astype(int)
print(ejemplo)

[1 0 0]


Esta construcción puede ser la base para registrar eventos cada minuto,
simular lecturas horarias, o generar columnas base en modelos de series
temporales.

### Uso con decimales

In [116]:
# También se puede utilizar np.arange() con pasos decimales, aunque con precaución:
fracciones = np.arange(0, 1, 0.2)
print(fracciones) # Resultado: [0. 0.2 0.4 0.6 0.8]

[0.  0.2 0.4 0.6 0.8]


¡Importante! El uso de pasos flotantes puede generar errores de precisión debido al manejo interno de punto flotante en computación. Para evitar esto
en contextos críticos, se recomienda np.linspace() (que permite definir el número exacto de puntos) y se revisará en sesiones posteriores.

### Verificación de tipo de datos

In [117]:
# El tipo de datos resultante dependerá de los valores entregados:
print(np.arange(0, 5, 1).dtype) # int64
print(np.arange(0, 1, 0.1).dtype) # float64

int64
float64


Esto es importante si se quiere controlar explícitamente el tipo de dato en
cálculos posteriores.

## Matrices de ceros np.zeros()

### Sintaxis básica:

np.zeros(formato, dtype=float)

- formato: tupla que define la forma del arreglo (filas, columnas). Tupla, es una estructura de datos unmutables, son con parentesis ()

- dtype (opcional): tipo de dato del arreglo (por defecto, float).

In [118]:
# matriz de ceros, 3 filas y 4 columnas, ideal para almacenar datos en una tabla de observaciones aún no completadas.
plantilla = np.zeros((3, 4), dtype= int) # si no especifico tipo dato entero por defecto lo deja como float
print(plantilla)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [119]:
plantilla.dtype

dtype('int64')

In [120]:
plantilla = np.zeros((3, 4)) # si no especifico tipo dato entero por defecto lo deja como float
print(plantilla) # 3 filas 4 columnas 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [121]:
plantilla.dtype

dtype('float64')

- Matriz cuadrada es la misma cantidad de filas y columnas ej: (2,2), (5,5)

## Creación de un vector de unos

In [122]:
# Esto genera un vector unidimensional de cinco elementos, todos con el valor 1.0. Por defecto, los datos son de tipo float64.
unos = np.ones(5)
print(unos)

[1. 1. 1. 1. 1.]


## Creación de una matriz de unos

In [123]:
# Esta matriz de 2 filas por 3 columnas puede utilizarse, por ejemplo, para simular un conjunto de observaciones iniciales idénticas.
estructura = np.ones((2, 3))
print(estructura)

[[1. 1. 1.]
 [1. 1. 1.]]


## Multiplicación por un escalar

Si se necesita una estructura homogénea con otro valor, basta multiplicar el resultado por el número deseado:

In [124]:
# Esto es útil para definir condiciones iniciales estables, constantes de prueba o patrones repetitivos.
matriz_unos = np.ones((2,3)) * 100
print(matriz_unos)

[[100. 100. 100.]
 [100. 100. 100.]]


### Cambiar tipo de datos (dtype)

Por defecto, np.ones() genera float64, pero puede especificarse otro tipo de datos:

Esto es relevante cuando se requieren operaciones discretas o ahorro de memoria.

In [125]:
unos_int = np.ones((3, 3), dtype=int)
print(unos_int)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Comparación con otras funciones de inicialización

Función Descripción

Ejemplo:

- np.zeros() Arreglo lleno de ceros np.zeros((2, 2))
- np.ones() Arreglo lleno de unos np.ones((2, 2))
- np.full() Arreglo con un valor específico np.full((2, 2), fill_value=7)

Esta comparación permite elegir con claridad la herramienta adecuada según el contexto de trabajo.

In [126]:
matriz_especial = (np.full((2, 2), fill_value=8))
matriz_especial

array([[8, 8],
       [8, 8]])

## Ejercicio

### Objetivo: 
Aplicar la creación de vectores, matrices y funciones automáticas de generación utilizando
NumPy, para estructurar datos simulados provenientes de sensores ambientales en un sistema de
monitoreo urbano.

### Situación: Trabajas en el área de desarrollo de un sistema automatizado de monitoreo de variables ambientales. 
Cada dispositivo desplegado en la ciudad registra lecturas continuas de temperatura,
humedad y concentración de partículas. Tu jefatura te solicita generar una estructura inicial que sirva para
simular, almacenar y procesar estos datos rápidamente en tiempo real, sin escribir cada dato manualmente
ni usar estructuras poco eficientes como listas anidadas.
Además, te piden dejar lista una plantilla vacía para almacenar futuras mediciones, así como un vector que
represente el estado inicial de calibración de todos los sensores.
Instrucciones

### Instrucciones
Crear un vector con una lectura individual (3 variables: temperatura, humedad, partículas)

In [127]:
# temperatura, humedad, partículas
lectura = np.array([22.5, 55.0, 83.1])
print(lectura)

[22.5 55.  83.1]


Crear una matriz con lecturas múltiples (4 registros de sensores)

In [128]:
# Cada fila representa una medición completa en un instante de tiempo.
# temperatura ( columna 0), humedad ( columna 1), partículas (columna 2)
lecturas = np.array([[22.5, 55.0, 83.1],[23.0, 54.5, 80.2],[21.8, 56.2, 84.7],[22.3, 55.8, 81.4]])
print("Lecturas múltiples: \n", lecturas)

Lecturas múltiples: 
 [[22.5 55.  83.1]
 [23.  54.5 80.2]
 [21.8 56.2 84.7]
 [22.3 55.8 81.4]]


¿Cómo puedes identificar la lectura con mayor nivel de partículas?

In [129]:
# tengo que ver la tercera columna que pertenece a partículas
particulas = lecturas[:,2] # mostrar todas las filas (:) y la columna 2
particulas

array([83.1, 80.2, 84.7, 81.4])

In [132]:
# Para saber el valor máximo
maximo = np.max(particulas)
print(maximo)

84.7


In [ ]:
# Para que me muestre la ubicación del indice donde se encuentra el valor máximo del vector particulas 
indice_maximo = np.argmax(particulas)
print(indice_maximo)

2


In [140]:
np.argmax (lecturas[:,2])

np.int64(2)

In [141]:
np.max(lecturas[:,2])

np.float64(84.7)

In [136]:
lecturas

array([[22.5, 55. , 83.1],
       [23. , 54.5, 80.2],
       [21.8, 56.2, 84.7],
       [22.3, 55.8, 81.4]])

In [ ]:
# cantidad de elementos de la matriz
lecturas.size

12

In [ ]:
# me muestra la ubicacion del valor maximo dentro de la matriz
max_matriz = np.argmax(lecturas) # va desde el 0 al indice 8 donde esta el valor máximo
print(max_matriz)

8


In [ ]:
# otro ejemplo
ejemplo = lecturas [:1,2] # de la fila 0 a la 1 ( sin considerar la fila 1) y la columna 2  = 83.1
ejemplo

array([83.1])

In [ ]:
ejemplo = lecturas [1:3,2] # de la fila 0 a la 3 ( sin considerar la fila 3) y la columna 2 partículas = 80.2(fila 1 columna 2), 84.7 (fila 2 columna 2)
ejemplo
ejemplo

array([80.2, 84.7])

In [ ]:
lecturas

array([[22.5, 55. , 83.1],
       [23. , 54.5, 80.2],
       [21.8, 56.2, 84.7],
       [22.3, 55.8, 81.4]])

In [ ]:
ejemplo = lecturas [:2,1] # debe traer la columna humedad/ la fila 0 y la 1 sin considerar la 2 y la columna 1 --- 55.0, 54.5
ejemplo

array([55. , 54.5])

In [ ]:
ejemplo = lecturas [1:3,1:3]  # trae la fila 1 y 2 (sin considerar la fila 3) y la columna 1 y 2( sin considerar la columna 3)
ejemplo

array([[54.5, 80.2],
       [56.2, 84.7]])

Crear una secuencia de tiempo que acompañe las mediciones

In [ ]:
# va desde 0 (inicio) a 4 min, porque las lecturas anteriores fueron 4 mediciones de 3 factores cada 1 min.
# 0,1,2 y 3 minutos (4 m3diciones de temperatura, humedad, partículas)
tiempo = np.arange(0, 4, 1)
print("Tiempos de lectura (minutos):", tiempo)

Tiempos de lectura (minutos): [0 1 2 3]


¿Y si los sensores midieran cada 15 segundos en vez de cada minuto?

¿Qué cambiaría?

In [145]:
''' 
1 min    60 seg
  x      15 seg

15 * 1 / 60 = 0.25 minutos  
'''

tiempo_15 = np.arange(0, 4, 0.25)
print("Tiempos de lectura (minutos):", tiempo_15)

Tiempos de lectura (minutos): [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75]


In [146]:
tiempo_15.size

16

Crear una plantilla vacía para almacenar futuras mediciones

In [147]:
# Estructura de 16 filas (futuras observaciones) y 3 columnas (variables ambientales).
plantilla = np.zeros((16,3))
print("Plantilla vacía para nuevas mediciones:", plantilla)

Plantilla vacía para nuevas mediciones: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Crear un vector de calibración con valores iniciales iguales a 1

In [148]:
calibracion = np.ones(3)
print("Vector de calibración inicial:", calibracion)

Vector de calibración inicial: [1. 1. 1.]
