## Indexación y selección: selección de elementos de un arreglo.

En NumPy, indexar significa acceder a uno o varios elementos de un arreglo (ndarray) utilizando sus posiciones. Esta capacidad es esencial cuando necesitamos leer, modificar o extraer datos específicos para analizarlos o procesarlos. A diferencia de las listas tradicionales de Python, NumPy ofrece una variedad de formas para indexar datos que permiten seleccionar elementos de forma precisa y eficiente, tanto en arreglos unidimensionales (vectores) como en arreglos bidimensionales (matrices).

### Indexación en arreglos unidimensionales

Supongamos que tienes un arreglo con datos de velocidad registrados por un sensor:

In [2]:
import numpy as np

In [3]:
velocidades = np.array([30, 45, 55, 60, 48, 52])

## Acceso por posición

Podemos acceder a un valor individual indicando su índice (comienza en 0):

In [4]:
print(velocidades[0]) # 30
print(velocidades[3]) # 60

30
60


## Índices negativos y rebanado

### Índices negativos

In [5]:
# También puedes usar índices negativos para contar desde el final:
print(velocidades[-1]) # 52 (último valor)
print(velocidades[-3]) # 60 (tercer valor desde el final)

52
60


### Rebanado o slicing

In [6]:
print(velocidades)

[30 45 55 60 48 52]


In [7]:
# Si necesitas extraer una porción del arreglo:
segmento = velocidades[1:4] # considera de la posición 1 a la 3
print(segmento) # [45 55 60]

[45 55 60]


In [8]:
segmento = velocidades [:3] # selecciona los tres primeros valores.
print(segmento)


[30 45 55]


In [9]:
#selecciona desde la posición 3 hasta el final. Sin necesidad de conocer el tamaño del arreglo
segmento = velocidades [3:] 
print(segmento)


[60 48 52]


## Indexación en arreglos bidimensionales (matrices)

Cuando trabajamos con matrices (dos dimensiones), la indexación requiere dos coordenadas: fila y columna

In [10]:
matriz = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matriz)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


### Acceso a elementos en matrices

In [11]:
# Acceso a un elemento específico
print(matriz[1, 2]) # 60 (segunda fila(corresponde al 1, ya que comienza de 0 la fila y las columns), tercera columna)

60


In [12]:
# Acceso a una fila completa
print(matriz[0]) # en este caso a la fila 0 o primera fila
print(matriz[0,:]) 

[10 20 30]
[10 20 30]


In [13]:
# Acceso a una columna completa
print(matriz[:,1]) #todos los elemnetos de la fila correspondiente a la columna 1(segunda columna de todas las filas)

[20 50 80]


## Modificación de valores mediante indexación

In [14]:
print(velocidades)

[30 45 55 60 48 52]


Podemos asignar nuevos valores usando índices:

In [15]:
# en un vector
velocidades[2] = 50
print(velocidades)

[30 45 50 60 48 52]


In [16]:
print(matriz)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [17]:
# en una matriz
matriz[1,1] = 88
print(matriz)

[[10 20 30]
 [40 88 60]
 [70 80 90]]


## Reemplazo de secciones y acceso avanzado

### Reemplazo de secciones completas

In [18]:
print(velocidades)

[30 45 50 60 48 52]


Es posible reemplazar un segmento completo del arreglo con nuevos valores:

In [19]:
velocidades[0:3] = [35, 46, 51]
print(velocidades)

[35 46 51 60 48 52]


❓ ¿Qué pasa si no coinciden?

Por ejemplo:

velocidades[0:3] = [35, 46]


Izquierda → 3 elementos

Derecha → 2 elementos

👉 No coinciden.

Resultado:

❌ NumPy lanza un error.

O al revés:

velocidades[0:3] = [35, 46, 51, 80]


Izquierda → 3 elementos

Derecha → 4 elementos

👉 Tampoco coincide.

❌ Error.

### Acceso con listas de índices

In [20]:
print(velocidades)

[35 46 51 60 48 52]


Puedes seleccionar posiciones específicas usando una lista:

Esto se denomina indexación avanzada y es útil para aplicar filtros personalizados.

In [21]:
print(velocidades)

[35 46 51 60 48 52]


In [22]:
tamaño= len(velocidades)
tamaño

6

In [23]:
posiciones = [0, 2, 4]
print(velocidades[posiciones])

[35 51 48]


## Indexación booleana

In [24]:
# que imprima las velocidades mayores a 50
print(velocidades[velocidades > 50])

[51 60 52]


In [25]:
print(matriz)

[[10 20 30]
 [40 88 60]
 [70 80 90]]


In [26]:
print(matriz[matriz>30])

[40 88 60 70 80 90]


### IMPORTANTE: 
Verificar dimensiones. Siempre revisa .shape y .ndim para confirmar las dimensiones del arreglo.