# Referencia y copia de arreglos en NumPy.

¿Qué sucede cuando asignas un arreglo a otra variable? ¿Es una copia o una referencia?

En Python, las variables funcionan como referencias a objetos en memoria. Cuando trabajamos con arreglos en NumPy, es
fundamental entender esta diferencia, ya que una asignación puede no crear una copia nueva, sino simplemente otro nombre que apunta al mismo arreglo original. Esto puede llevar a errores sutiles y difíciles de detectar si se modifican datos sin
intención.

In [1]:
import numpy as np

## Asignación directa: referencia al mismo arreglo

In [2]:
a = np.array([1,2,3])
b = a # No se crea una copia, b apunta al mismo arreglo
b[0] = 100
print("a:", a) # Resultado: [100 2 3]
print("b:", b) # Resultado: [100 2 3]


a: [100   2   3]
b: [100   2   3]


In [3]:
c = np.array([10,20,30])
d = np.arange(10,20,4)

print(c)
print(d)

[10 20 30]
[10 14 18]


¿Qué ocurrió? 

Al modificar b, también se modificó a, porque ambas
variables referencian exactamente el mismo objeto en memoria. Esto
se denomina aliasing.

### ¿Cómo verificar si dos arreglos comparten memoria?

Podemos usar np.shares_memory() para confirmar si dos arreglos apuntan al mismo bloque de datos:

In [4]:
np.shares_memory(a,b)

True

In [5]:
np.shares_memory(c,d)

False

# Crear una copia real del arreglo 

Si deseamos trabajar con una copia completamente independiente, debemos usar el método .copy():

In [19]:
print(a)

[100   2   3]


In [10]:
copia = a.copy()
print(copia)

[100   2   3]


In [ ]:
copia[0] = 999
print('a:', a)
print('copia:', copia)

# Ahora, copia es una nueva estructura de datos, y los cambios en ella no afectan a a.

a: [100   2   3]
copia: [999   2   3]


# Copias en matrices: el caso con slicing

In [14]:
matriz = np.array([[1, 2], [3, 4]])
submatriz = matriz[:, 0] # Selecciona la primera columna
print("submatriz:\n", submatriz)

submatriz:
 [1 3]


In [20]:
submatriz[0] = 100
print("matriz:\n", matriz)
print("submatriz:\n", submatriz)

matriz:
 [[1 2]
 [3 4]]
submatriz:
 [100   3]


Esto sucede porque submatriz no es una copia independiente, sino una vista (view) sobre la matriz original.

# Cómo hacer una copia segura de una subestructura

In [18]:
# al hacer el copy no afectaria las modificaciones de submatriz sin afectar la original
matriz = np.array([[1,2],[3,4]])
submatriz = matriz[:,0].copy()
submatriz[0]= 200
print("matriz:\n", matriz)
print("submatriz:\n", submatriz)

matriz:
 [[1 2]
 [3 4]]
submatriz:
 [200   3]


¿Por qué es importante esto?

En ciencia de datos, es común transformar, limpiar y reestructurar datos. Si no distinguimos entre copiar y referenciar, podríamos:

• Corromper el conjunto de datos original por accidente.

• Propagar errores silenciosos en análisis.

• Obtener resultados inconsistentes en modelos o simulaciones.