# Selección condicional de elementos de un arreglo.

En análisis de datos, es común tener que filtrar los valores que
cumplen una cierta condición: por ejemplo, seleccionar solo los
valores mayores a un umbral, encontrar los elementos que cumplan
múltiples criterios o extraer filas específicas de una matriz que
cumplan con cierta lógica. NumPy facilita este proceso mediante una
técnica llamada indexación booleana, que permite seleccionar
subconjuntos de datos en base a expresiones lógicas.

## Condiciones sobre arreglos unidimensionales

In [1]:
import numpy as np

In [2]:
# Supongamos que tienes un vector con registros de temperatura:
temperaturas = np.array([22.5, 25.0, 19.8, 27.3, 21.0])

## Aplicar una condición

Podemos generar un arreglo de valores True o False indicando si cada
elemento cumple la condición:

In [ ]:
# recorre el vector e indica True cuando la condicion es verdadera y False cuando es falsa y entrega un vector
condicion = temperaturas > 23
print(condicion)

[False  True False  True False]


### Usar la condición como índice

In [ ]:
# imprime las temperaturas que cumplen la condicion guardada en la variable condicion, en este caso > 23
print(temperaturas[condicion])

[25.  27.3]


In [ ]:
# para seleccionar los que no cumplen con la condición // ~ simbolo para la negación
print(temperaturas[~condicion])

[22.5 19.8 21. ]


### Expresión compacta

Este enfoque nos permite filtrar automáticamente los datos.

Podemos hacer todo en una sola línea:

In [7]:
# sobre el arreglo temperaturas realizo la condición temperaturas > 23
print(temperaturas[temperaturas > 23])

[25.  27.3]


In [10]:
print(temperaturas[temperaturas < 21])
print(temperaturas[temperaturas == 25])
print(temperaturas[temperaturas != 22.5])

[19.8]
[25.]
[25.  19.8 27.3 21. ]


## Múltiples condiciones (combinadas)

Podemos combinar condiciones con los operadores lógicos de NumPy:

• & significa AND lógico

• | significa OR lógico

• ~ significa NOT lógico

#### ¡Importante! Los paréntesis son obligatorios para que Python evalúe correctamente la operación.

Ejemplo: seleccionar temperaturas mayores a 20 y menores a 26

In [13]:
print(temperaturas)

[22.5 25.  19.8 27.3 21. ]


In [12]:
condicion = (temperaturas > 20) & (temperaturas < 26)
print(condicion)
print(temperaturas[condicion])

[ True  True False False  True]
[22.5 25.  21. ]


In [16]:
condicion = (temperaturas > 23) | (temperaturas == 22)
print(temperaturas[condicion])

[25.  27.3]


In [18]:
condicion = ~(temperaturas > 21)
print(temperaturas[condicion])

[19.8 21. ]


In [19]:
print(temperaturas[~(temperaturas > 23)])

[22.5 19.8 21. ]


## Condiciones sobre matrices

También podemos aplicar condiciones a matrices completas. Supongamos:

In [28]:
matriz = np.array([[11,20,33],[48,53,62],[74,88,95]])
print(matriz)

[[11 20 33]
 [48 53 62]
 [74 88 95]]


In [32]:
# Obtener los elementos mayores a 20
print(matriz[matriz > 20])

[33 48 53 62 74 88 95]


Esto devuelve un vector con todos los elementos que cumplen la condición.

In [29]:
print(matriz[~(matriz < 35)])

[48 53 62 74 88 95]


## Máscaras booleanas reutilizables

In [30]:
# condicion, imprimir números pares de la matriz
pares = (matriz % 2 == 0)
print(matriz[pares])

[20 48 62 74 88]


In [31]:
impares = (matriz % 2 == 0)
print(matriz[~(pares)])

[11 33 53 95]


## Filtrado combinado con asignación

Podemos usar condiciones no solo para seleccionar, sino también para modificar:

In [33]:
print(temperaturas)

[22.5 25.  19.8 27.3 21. ]


In [35]:
temperaturas[temperaturas > 22] = 22
print(temperaturas)

[22.  22.  19.8 22.  21. ]


Esto es útil en limpieza de datos, imputación de valores mínimos o normalización.